INSERT INTO ACCOUNT (ID, FIRST_NAME, LAST_NAME) VALUES(1, 'Max', 'Mustermann');
INSERT INTO ACCOUNT (ID, FIRST_NAME, LAST_NAME) VALUES(2, 'Darth', 'Vader');
INSERT INTO ACCOUNT (ID, FIRST_NAME, LAST_NAME) VALUES(3, 'Amal', 'James');